[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'AtsushiM/search-parent.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
	if dein#util#_is_windows()
		let cmd = 'tools\\update-dll-mingw'
	elseif dein#util#_is_cygwin()
		let cmd = 'make -f make_cygwin.mak'
	elseif dein#util#_is_mac()
		let cmd = 'make -f make_mac.mak'
	else
		let cmd = 'gmake'
	endif
	let g:dein#plugin.build = cmd
	'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
