[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'AtsushiM/search-parent.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
