[[plugins]]
repo ='Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'tweekmonster/deoplete-clang2'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'

[[plugins]]
repo ='Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

##[[plugins]]
##repo = 'zchee/deoplete-jedi'
##
##[[plugins]]
##repo = 'zchee/deoplete-go'
##'build' =  'make'

[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'drzel/vim-line-no-indicator'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'mattn/emmet-vim'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
